Update index.md
StrataSource/Wiki pull request #27
Opened 2023-04-10 17:03 UTC by Equalizer5118

Updated name usage to strata

2023-04-10 17:26 UTC, tsa96 requested changes

2023-04-10 17:26 UTC, tsa96 commented on index.md
> +Welcome to the Strata Sourceengine wiki! This wiki contains documentation that is
Missing space - "Sourceengine"

2023-04-10 17:37 UTC, Equalizer5118 commented on index.md
> +Welcome to the Strata Sourceengine wiki! This wiki contains documentation that is
Aight, fixed. Thanks man.

2023-04-10 20:52 UTC, tsa96 requested changes
You should use the .svg version of the favicon at well, that one adapts to whether the user is using light or dark mode

2023-04-11 01:10 UTC, Equalizer5118 commented
Alright, removed old ico and added svg instead. What do you think?

2023-04-11 01:14 UTC, tsa96 commented
Not sure where you got that SVG from, the dynamic SVG is https://github.com/StrataSource/strata-branding/blob/main/i/favicon.svg

Sorry if hard to find, not really sure what's going on with the Strata branding tool tbh. But that one I linked should be used for all favicons.

You should still include an ICO favicon though, for browsers that don't support SVGs.

2023-04-11 01:15 UTC, tsa96 commented
And you'll need to actually update the HTML to add it. Maybe worth pinging me on someone else in Discord if you're not familiar with HTML

2023-04-11 01:25 UTC, Equalizer5118 commented
Alright, I'll do that. I'm still learning HTML and GitHub, so I apologize for my inability to do this efficiently.

2023-04-11 01:48 UTC, tsa96 approved these changes

2023-04-11 01:49 UTC, tsa96 commented
Looks okay, though I don't have a local setup to test this. JJ can you check it out, or just squash (def worth squashing, commit history is gross) it if you're happy?

2023-04-11 02:00 UTC, Equalizer5118 commented
I tested this locally and everything checks out on my end

2023-05-06 03:54 UTC, JJL772 approved these changes
Oh whoops, didn't see the "pls review" email from github!

Looks good to me, thanks for updating this for us!

2023-05-06 03:55 UTC, merged